# Generated by Django 5.0.7 on 2024-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0004_student_father_name_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
