# Generated by Django 5.0.7 on 2024-08-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0005_alter_student_email_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='exams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_app.exams'),
        ),
    ]
